### ISSUE TITLE
Issues with the positioning of the widget?

### ISSUE THREAD

**Issue by xxJuiceboxx1** [Pe8er/Sidebar.Widget#10]
The widget seems to be conflicting with clock widget. Is there a way to reposition the widget?

![image](https://cloud.githubusercontent.com/assets/20021804/16175044/87f7df36-3624-11e6-9c2b-6982fbd2a48e.png)

**Comment by Pe8er** [comment]
Yes, you can. You need to open `Sidebar.widget/index.coffee` and mess around with values at the top. There is a URL to a great flexbox reference page at the top of the document too.

**Comment by PixelPirate** [comment]
Hmm.. I'm having issues as well, using `Sidebar.Widget` works fine, but as soon as I add any other Widget everything gets screwed up.

I'm no web-dev by any means, so this is giving me a really hard time to debug. Can anyone explain why `Sidebar.Widget` screws with other widgets positioning and can anyone give a pointer as to how to resolve this?

**Comment by Pe8er** [comment]
@PixelPirate is there anything else I can help you with here?
