### ISSUE TITLE
Issue with transparency?

### ISSUE THREAD

**Issue by Esgal** [Pe8er/Sidebar.Widget#11]
I have a couple more widgets on the desktop, mainly trash size and a clock. 
I have managed to set the other widgets as transparent, but when I add the Sidebar every widget gets a solid black background - do you have any idea on what's going on?

**Comment by sc0tt13** [comment]
Same problem here. The background seems to apply to all the widgets, is there some kind of "absolute" trick to get around it (like for the positioning)?

**Comment by Pe8er** [comment]
Hey guys,

You are on the right track. `index.coffee` in main widget folder has some CSS which applies to all widgets:

```
    .widget {
      position: relative;
      background-color: rgba(0,0,0,.2);
      -webkit-backdrop-filter: blur(30px) brightness(80%) contrast(100%) saturate(140%);
      margin-top: 1px;
    }
```
