### ISSUE TITLE
Spotify reopens immediately after quitting

### ISSUE THREAD

**Issue by dominiklohmann** [Pe8er/Sidebar.Widget#7]
When running `Playbox.widget`, Spotify.app reopens directly after quitting the application.

**Comment by Pe8er** [comment]
I've just pushed some updates which stop this from happening on my system. Check it out and let me know what happens!

https://github.com/Pe8er/Sidebar.Widget/blob/master/Sidebar.widget.zip?raw=true

**Comment by dominiklohmann** [comment]
That works, tyvm. 

One more question, does the progress bar work for you with Spotify? I can't get it to work, always seems to be stuck at 100%.

**Comment by Pe8er** [comment]
Ha, nice catch! Just fixed it, please redownload.

**Comment by schaufma** [comment]
GREAT … everythin is fine now!

Thanks for the work ..

**Comment by dominiklohmann** [comment]
Progress bar is still stuck at 100% for me.

**Comment by Pe8er** [comment]
@dominiklohmann please do the following:

1. Make sure you have the latest version of the widget.
1. Restart Ubersicht.
1. Open `Sidebar.widget/Playbox.widget/as/Get Current Track.applescript` in Script Editor.
1. Make sure there is a song playing.
1. Hit ⌘ + R to run the Applescript.
1. Copy output from Result area at the bottom of the window.
1. Wait a few seconds.
1. Run it again and copy output again.
1. Paste both outputs here.

**Comment by dominiklohmann** [comment]
``` 
❯ osascript Get\ Current\ Track.applescript
Zhu ~ In the Morning ~ In the Morning ~ ★★★☆☆ ~ 246495 ~ 4,242 ~ http://img2-ak.lst.fm/i/u/174s/7a424d57923b933ee4466a5d09f328ec.png

❯ osascript Get\ Current\ Track.applescript
Zhu ~ In the Morning ~ In the Morning ~ ★★★☆☆ ~ 246495 ~ 28,143 ~ http://img2-ak.lst.fm/i/u/174s/7a424d57923b933ee4466a5d09f328ec.png
```

**Comment by Pe8er** [comment]
Thanks. Try the [latest version](https://github.com/Pe8er/Sidebar.Widget/blob/master/Sidebar.widget.zip?raw=true)!

**Comment by Pe8er** [comment]
I think I've fixed it. Please try [the latest version](https://github.com/Pe8er/Sidebar.Widget/blob/master/Sidebar.widget.zip?raw=true) and let me know.

**Comment by dominiklohmann** [comment]
Nope. 

![screen shot 2016-03-14 at 19 13 58](https://cloud.githubusercontent.com/assets/4488655/13754907/0c63ed4e-ea19-11e5-8e1b-1ae155279c27.png)

```
❯ osascript Get\ Current\ Track.applescript
Zhu ~ Working For It ~ Genesis Series ~ ★★★★☆ ~ 231813 ~ 46,668 ~ http://img2-ak.lst.fm/i/u/174s/58133fd85084c763dda6ceec9dd2b1ef.png
❯ osascript Get\ Current\ Track.applescript
Zhu ~ Working For It ~ Genesis Series ~ ★★★★☆ ~ 231813 ~ 56,725 ~ http://img2-ak.lst.fm/i/u/174s/58133fd85084c763dda6ceec9dd2b1ef.png
```

**Comment by Pe8er** [comment]
Please run this in Script Editor:

```
set oValues to {}
tell application "Spotify"
	repeat 3 times
		set aDuration to duration of current track
		set aPosition to player position
		copy aPosition & aDuration to the end of oValues
		delay 1
	end repeat
end tell

return oValues
```

**Comment by dominiklohmann** [comment]
`{{137.622, 231813}, {138.623, 231813}, {139.625, 231813}}` seems to work.

**Comment by Pe8er** [comment]
Alright. I fixed number formatting in the latest version. It looks like we managed to miss each other — I probably pushed the latest update seconds after you downloaded it. Try downloading it again.

**Comment by dominiklohmann** [comment]
Completely forgot to close this, sorry for leaving it open so long.

**Comment by Pe8er** [comment]
No worries @dominiklohmann :smile:
