### ISSUE TITLE
Repositioning?

### ISSUE THREAD

**Issue by AndyG1128** [Pe8er/Sidebar.Widget#8]
I want to preface this by stating I am very new to Coffee Script and Java, so my question comes from not knowing where to look most likely.

I have been through the link on Flexbox properties and I have scoured the scripts and I just cannot figure out how to move this from the right bottom to the left top of the screen. What am i missing?

**Comment by AndyG1128** [comment]
Never Mind, I finally figured it out while playing a bit more with the flex settings.  I didn't realize the whole screen was the flex box.  Thanks for the scripts and intro to this form of formatting.  I have a lot to learn.

**Comment by Pe8er** [comment]
Ha, I'm glad you worked it out!

**Comment by AndyG1128** [comment]
It was a little counter intuitive, but once I figured out the whole screen was the box, it made sense.

Now I get to play with it and my other widgets that seem to want to attach to the sidebar like a magnet, lol

I think I am going to play with the others to either include them in the flex box or see if I can find how to break them free of the flexbox’s influence

Still learning Coffee and CSS so this will be a good learning experience
